<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/vendor/composer/autoload_real.php';

if ( !file_exists( __DIR__.'/config/salt.config.php' ){
	file_put_contents( 
		              __DIR__.'/config/salt.config.php', 
                      file_get_contents('https://api.wordpress.org/secret-key/1.1/salt/')
                     );
}

return ComposerAutoloaderInit76b665c088cb8d8dbd0efa2f94a994fd::getLoader();
