<?php

// autoload.php @IS NOT generated by MotherFuck Composer

/**
*
* InterActivePlus OpenAPI Autoload
*
* @version 0.1
* @author GHL(Liuxing)
* Standard @link { https://github.com/InteractivePlus/InterActivePDK2019-DesignDoc/tree/master/CodingStructures/Backend }
*
* This File Help to load the OpenAPI System automatically
*
**/

require_once __DIR__ . '/vendor/autoload.php';

if ( !file_exists( XSYD\Config\$config['dir'].'/salt.config.php') ){
   $_Content = '<?php 
   '.file_get_contents('https://api.wordpress.org/secret-key/1.1/salt/');
   file_put_contents( XSYD\Config\$config['dir'].'/salt.config.php', $_Content);
   unset($_Content);
}

foreach ( XSYD\Config\$config['files'] as  $_IncludeConfigFiles ) {
	require XSYD\Config\$config['dir']."/$_IncludeConfigFiles";
}
