<?php

// autoload.php @IS NOT generated by MotherFuck Composer

/**
*
* InterActivePlus OpenAPI Autoload
*
* @version 0.1
* @author GHL(Liuxing)
* Standard @link { https://github.com/InteractivePlus/InterActivePDK2019-DesignDoc/tree/master/CodingStructures/Backend }
*
* This File Help to load the OpenAPI System automatically
*
**/

require_once __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/config/general.config.php';

if ( !file_exists( XSYD_CONFIG_PATH.'/salt.config.php') ){
   $_Salt = \XSYD\Password\SecureRandom::GenSalt();
   $_Content = <<<EOF 
				<?php
				define('AUTH_SALT',$_Salt);
				?>
  				  EOF;
   file_put_contents( XSYD_CONFIG_PATH.'/salt.config.php', $_Content);
   unset($_Content,$_Salt);
}

foreach ( $_Files as  $_IncludeConfigFiles ) {
	require XSYD_CONFIG_PATH."/$_IncludeConfigFiles";
}
